apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-agent
  name: onprem-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-agent
  namespace: onprem-system
  labels:
    control-plane: controller-agent
spec:
  selector:
    matchLabels:
      control-plane: controller-agent
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-agent
    spec:
      serviceAccountName: controller-agent
      containers:
      - command:
        - /agent
        image: quay.io/ifont/onprem-agent:latest
        name: agent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: hub-cluster-secret
          mountPath: /etc/hub-cluster-secret
          readOnly: true
        - name: hub-cluster-configmap
          mountPath: etc/hub-cluster-configmap
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: hub-cluster-secret
        secret:
          secretName: hub-cluster
      - name: hub-cluster-configmap
        configMap:
          name: hub-cluster
---
# controller agent sa and rolebinding
piVersion: v1
kind: ServiceAccount
metadata:
  name: controller-agent
  namespace: onprem-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-agent-admin
  namespace: onprem-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: controller-agent
---
# bootstrap sa, cluster role and binding
piVersion: v1
kind: ServiceAccount
metadata:
  name: onprem-bootstrap-sa
  namespace: onprem-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onprem-bootstrap-role
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onprem-bootstrap-clusterrolebinding
  namespace: onprem-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onprem-bootstrap-role
subjects:
- kind: ServiceAccount
  name: onprem-bootstrap-sa
