apiVersion: clustermanager.onprem.openshift.io/v1alpha1
kind: MultiClusterWorkload
metadata:
  name: multiclusterworkload-sample
spec:
  template: |-
   --- 
   kind: Deployment
   apiVersion: extensions/v1beta1
   metadata:
     name: nginx-deployment
   spec:
     replicas: 3
     strategy: Recreate
     selector:
       matchLabels:
         deploy: example
     template:
       metadata:
         labels:
           deploy: example
       spec:
         containers:
           - name: nginx
             image: nginx:1.7.9
    ---
  serviceaccount: gcp-serviceaccount
  placement:
  - gcp-cluster1
  - gcp-cluster2
  - aws-cluster3   
status:
  singleClusterWorkloads:
  - onprem-system/gcp-cluster1-workload
  - example-system/gcp-cluster2-workload
